### ISSUE TITLE
Rename to DISCORD_TOKEN

### ISSUE THREAD

**Issue by ryanRfox** [Cryptonite-Group-Inc/mezo-drip-hackathon-bot-demo#2]
currently there is a mismatch between the key named __"DISCORD_TOKEN"__ within the `.env` file and code within the `bot.py` file:

`bot.run(os.getenv("TOKEN"))`

Workaround:
within `bot.py` rename to __"DISCORD_TOKEN"__ from __"TOKEN"__

**Comment by likemyRPG** [comment]
Updated the README, thanks!
